/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface HelloDefiAAVE2FactoryContract
  extends Truffle.Contract<HelloDefiAAVE2FactoryInstance> {
  "new"(
    _aaveILendingPoolAddress: string,
    meta?: Truffle.TransactionDetails
  ): Promise<HelloDefiAAVE2FactoryInstance>;
}

type AllEvents = never;

export interface HelloDefiAAVE2FactoryInstance
  extends Truffle.ContractInstance {
  userContracts(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  createClone: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<string>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  methods: {
    userContracts(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    createClone: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<string>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
