/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ERC20Contract } from "./ERC20";
import { HelloDefiAAVE2Contract } from "./HelloDefiAAVE2";
import { HelloDefiAAVE2FactoryContract } from "./HelloDefiAAVE2Factory";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IERC20PermitContract } from "./IERC20Permit";
import { ILendingPoolAAVE2Contract } from "./ILendingPoolAAVE2";
import { InitializableContract } from "./Initializable";
import { MockERC20Contract } from "./MockERC20";
import { MockLendingPoolAAVE2Contract } from "./MockLendingPoolAAVE2";
import { OwnableContract } from "./Ownable";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ERC20"): ERC20Contract;
      require(name: "HelloDefiAAVE2"): HelloDefiAAVE2Contract;
      require(name: "HelloDefiAAVE2Factory"): HelloDefiAAVE2FactoryContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC20Permit"): IERC20PermitContract;
      require(name: "ILendingPoolAAVE2"): ILendingPoolAAVE2Contract;
      require(name: "Initializable"): InitializableContract;
      require(name: "MockERC20"): MockERC20Contract;
      require(name: "MockLendingPoolAAVE2"): MockLendingPoolAAVE2Contract;
      require(name: "Ownable"): OwnableContract;
    }
  }
}

export { ERC20Contract, ERC20Instance } from "./ERC20";
export {
  HelloDefiAAVE2Contract,
  HelloDefiAAVE2Instance,
} from "./HelloDefiAAVE2";
export {
  HelloDefiAAVE2FactoryContract,
  HelloDefiAAVE2FactoryInstance,
} from "./HelloDefiAAVE2Factory";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IERC20PermitContract, IERC20PermitInstance } from "./IERC20Permit";
export {
  ILendingPoolAAVE2Contract,
  ILendingPoolAAVE2Instance,
} from "./ILendingPoolAAVE2";
export { InitializableContract, InitializableInstance } from "./Initializable";
export { MockERC20Contract, MockERC20Instance } from "./MockERC20";
export {
  MockLendingPoolAAVE2Contract,
  MockLendingPoolAAVE2Instance,
} from "./MockLendingPoolAAVE2";
export { OwnableContract, OwnableInstance } from "./Ownable";
